//SEARCH ACTIONS
export const GET_MESSAGE = 'GET_MESSAGE';
export const POSTCODE_UPDATE = 'POSTCODE_UPDATE';
export const POSTCODE_FAIL = 'POSTCODE_FAIL';
export const GET_DATA = 'GET_DATA';

//STATS ACTIONS
export const UPDATE_STATS_CONTAINER = 'UPDATE_STATS_CONTAINER';

//UI ACTIONS
export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const CLEAR_DIALOG = 'CLEAR_DIALOG';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const SHOW_LOADING = 'SHOW_LOADING';
